services:
  # See https://render.com/docs/blueprint-spec for more info on render blueprints
  - type: web
    name: dashboard-col-mortalidad
    env: python
    plan: free
    # A requirements.txt file must exist
    buildCommand: pip install -r requirements.txt
    # A src/app.py file must exist and contain `server=app.server`
    startCommand: gunicorn src.app:server --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        value: 8050
